name: fluttertools
description: A sample command-line application.
version: 0.0.1
repository: https://github.com/50ShadesOfCode/fluttertools

environment:
  sdk: ^3.0.6

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
